### ISSUE TITLE
What is username and password

### ISSUE THREAD

**Issue by brooda** [aws-samples/rag-using-langchain-amazon-bedrock-and-opensearch#10]
Hi, when I run terraform, it outputs the opensearch domain that I should use and it asks me about username and password. I don't know wherre from to get it. The documentation does not say it explicitely in my opinion. How should I do it?

Maybe I don't understand something here. Do I need already need to be somehow logged in before I run terraform command? On behalf of which AWS user is created this resource?

**Comment by omerh** [comment]
Hey @brooda 
The password is being generated in terraform [here](https://github.com/aws-samples/rag-using-langchain-amazon-bedrock-and-opensearch/blob/main/terraform/secret.tf) and stored in AWS Secret manager. To use the secret, I am getting it by its prefix [here](https://github.com/aws-samples/rag-using-langchain-amazon-bedrock-and-opensearch/blob/main/utils/secret.py).

The default index name is **rag**, and its also the username for OpenSearch, and I am retrieving it [here](https://github.com/aws-samples/rag-using-langchain-amazon-bedrock-and-opensearch/blob/7ae94870026b13236b475bc523f01d4f92ae8725/ask-bedrock-with-rag.py#L78).

Please let me know that its ok, and I will close the issue
