### ISSUE TITLE
Where can I found the embedding vector in the OpenSearch Dashboards?

### ISSUE THREAD

**Issue by Jiegenglyu** [aws-samples/rag-using-langchain-amazon-bedrock-and-opensearch#6]
I am confused at founding embedding vector in OpenSearch Dashboards, after I use the code to bulk the text and embedding vector into the OpenSearch
For further information, I found the chunked text in [Query Workbench], but can not found the embedding vector, I woulf be greatful for anyone's help.

**Comment by omerh** [comment]
You need to create a new index mapping in the admin, Kibana will identify the filed as other, but it will be visibile in the dashboard.

**Comment by omerh** [comment]
@Jiegenglyu were you able to find the documents in the dashboard? May I close the issue?
